"""
aubie_offline.py — AUBIEETERNAL Offline Runner
================================================
CC0 Public Domain — run this on any laptop.
No StartOS. No server. Just Python + Ollama.

REQUIREMENTS:
    pip install streamlit requests
    ollama pull qwen2.5:7b   # or 14b if you have RAM

USAGE:
    python3 aubie_offline.py

    # Or specify a model:
    AUBIE_MODEL=qwen2.5:14b python3 aubie_offline.py

    # Or point to a running Ollama instance:
    AUBIE_OLLAMA=http://192.168.1.251:11434 python3 aubie_offline.py

This runner includes:
  - All 106 lessons from the AUBIEETERNAL curriculum
  - Family stats saved locally to ~/.aubieeternal/
  - Daily quests with XP and streaks
  - AI Honesty scoring on all outputs
  - Morning synthesis (if run at 6AM)
  - Living Lattice signal publishing (opt-in)

Everything runs locally. No cloud. No subscription. No API key required.
The full sovereign stack in one file.

License: CC0 1.0 Universal — Public Domain Dedication
Source: https://github.com/AUBIEETERNAL-INSTITUTE-INC/AUBIEETERNAL
"""

import os, sys, json, subprocess, datetime
from pathlib import Path

# ── Config from environment ────────────────────────────────────────────────────
OLLAMA_URL   = os.environ.get("AUBIE_OLLAMA", "http://localhost:11434")
OLLAMA_MODEL = os.environ.get("AUBIE_MODEL",  "qwen2.5:7b")
DATA_DIR     = Path(os.environ.get("AUBIE_DATA",
                    os.path.expanduser("~/.aubieeternal/main")))
DATA_DIR.mkdir(parents=True, exist_ok=True)
(DATA_DIR / "families").mkdir(exist_ok=True)
PORT         = int(os.environ.get("AUBIE_PORT", "8501"))

BANNER = r"""
╔═══════════════════════════════════════════════════════════╗
║   🦅  A U B I E E T E R N A L  —  Offline Edition        ║
║   Sovereign Family Epistemic Practice                     ║
║   CC0 Public Domain — War Eagle Eternal                   ║
╚═══════════════════════════════════════════════════════════╝
"""

def check_dependencies():
    """Check Python packages and Ollama."""
    print(BANNER)
    print("Checking dependencies...")

    missing = []
    for pkg in ["streamlit", "requests"]:
        try:
            __import__(pkg)
        except ImportError:
            missing.append(pkg)

    if missing:
        print(f"\n❌ Missing packages: {', '.join(missing)}")
        print(f"Fix: pip install {' '.join(missing)}")
        sys.exit(1)

    # Check Ollama
    import requests
    try:
        r = requests.get(f"{OLLAMA_URL}/api/tags", timeout=3)
        models = [m["name"] for m in r.json().get("models", [])]
        if not models:
            print(f"\n⚠️  Ollama is running but no models found.")
            print(f"Fix: ollama pull {OLLAMA_MODEL}")
        else:
            print(f"✅ Ollama: {len(models)} models available")
            if OLLAMA_MODEL in models or any(OLLAMA_MODEL.split(":")[0] in m for m in models):
                print(f"✅ Model {OLLAMA_MODEL} ready")
            else:
                print(f"⚠️  Model {OLLAMA_MODEL} not found. Available: {models}")
                print(f"   Run: ollama pull {OLLAMA_MODEL}")
                print(f"   Or set: AUBIE_MODEL=<available_model>")
    except Exception:
        print(f"\n⚠️  Ollama not found at {OLLAMA_URL}")
        print("   Install: https://ollama.ai")
        print(f"   Then:    ollama pull {OLLAMA_MODEL}")
        print("   App will still launch — AI features will show a warning.")

    print(f"✅ Data dir: {DATA_DIR}")
    print(f"✅ All checks done\n")


def write_offline_app():
    """Write the offline Streamlit app to a temp file."""
    app_code = f'''"""AUBIEETERNAL Offline App — auto-generated by aubie_offline.py"""
import streamlit as st, json, os, requests, datetime, sys
from pathlib import Path

# ── Config ────────────────────────────────────────────────────────────────────
OLLAMA_URL   = "{OLLAMA_URL}/v1/chat/completions"
OLLAMA_MODEL = "{OLLAMA_MODEL}"
DATA_DIR     = Path("{DATA_DIR}")
FAMILIES_DIR = DATA_DIR / "families"
FAMILIES_DIR.mkdir(parents=True, exist_ok=True)
_TRUTH_LOG   = DATA_DIR / "truth_log.jsonl"

# ── Add parent dir to path so family_hud, family_profiles etc. are importable
sys.path.insert(0, str(Path(__file__).parent))

st.set_page_config(page_title="AUBIEETERNAL", page_icon="🦅", layout="wide")

# ── Dark theme CSS ─────────────────────────────────────────────────────────────
st.markdown("""<style>
.main {{background-color: #0a0e1a;}}
.stApp {{background-color: #0a0e1a; color: #c8d8ff;}}
h1,h2,h3 {{color: #c8d8ff; font-family: monospace;}}
.stButton button {{background: #1a2233; color: #c8d8ff; border: 1px solid #2a3550;}}
.stButton button:hover {{background: #2a3550;}}
</style>""", unsafe_allow_html=True)

# ── Sidebar ────────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("## 🦅 AUBIEETERNAL")
    st.markdown(f"*Offline Edition*")
    st.markdown(f"Model: `{{OLLAMA_MODEL}}`")
    st.markdown(f"Data: `{{DATA_DIR}}`")
    st.markdown("---")

    # Family selection
    _families = ["alpha", "beta", "gamma", "delta"]
    _fam = st.selectbox("Family", _families, key="offline_family")
    st.markdown("---")

    _page = st.radio("Navigate", [
        "🏠 Home",
        "📚 School",
        "🎮 Daily Quests",
        "🔮 Oracle",
        "📊 Dashboard",
        "🕸️ Living Lattice",
    ])

# ── Load family stats ──────────────────────────────────────────────────────────
def _load(fid):
    p = FAMILIES_DIR / f"{{fid}}.json"
    if p.exists():
        try: return json.loads(p.read_text())
        except: pass
    return {{"family_id":fid,"total_xp":0,"level":1,"badges":[],
              "lessons_completed":[],"streak_days":0,"last_session_date":"",
              "child_rune_fragments":0,"coherence_history":[]}}

def _save(stats, fid):
    p = FAMILIES_DIR / f"{{fid}}.json"
    stats["last_updated"] = datetime.datetime.now().isoformat()
    p.write_text(json.dumps(stats, indent=2))

def _ask_ollama(prompt, system=""):
    try:
        msgs = []
        if system: msgs.append({{"role":"system","content":system}})
        msgs.append({{"role":"user","content":prompt}})
        r = requests.post(OLLAMA_URL,
            json={{"model":OLLAMA_MODEL,"messages":msgs,"stream":False,"temperature":0.7}},
            timeout=120)
        if r.status_code == 200:
            return r.json()["choices"][0]["message"]["content"].strip()
        return f"⚠️ Ollama returned {{r.status_code}}"
    except Exception as e:
        return f"⚠️ Ollama not available: {{e}}"

stats = _load(_fam)

# ══════════════════════════════════════════════════════════════════════════════
if "Home" in _page:
    st.title("🦅 AUBIEETERNAL — Offline Edition")
    st.markdown(f"**Family:** {{_fam.title()}} &nbsp;|&nbsp; **Level:** {{stats.get(\'level\',1)}} &nbsp;|&nbsp; **XP:** {{stats.get(\'total_xp\',0)}}")
    st.progress(min(1.0, stats.get(\'child_rune_fragments\',0)/256),
                text=f"Child Rune: {{stats.get(\'child_rune_fragments\',0)}}/256 confirmations")

    c1,c2,c3,c4 = st.columns(4)
    c1.metric("Level", stats.get("level",1))
    c2.metric("Streak", f"{{stats.get(\'streak_days\',0)}}🔥")
    c3.metric("Lessons", len(stats.get("lessons_completed",[])))
    c4.metric("Badges", len(stats.get("badges",[])))

    st.markdown("---")
    st.markdown("""
    **What this is:**
    A sovereign family epistemic practice — 106 lessons, daily quests,
    AI tutor, steelmanning exercises, and on-chain identity via Bitcoin Runes.

    Running locally on your machine. No cloud. No subscription.
    Full source: https://github.com/AUBIEETERNAL-INSTITUTE-INC/AUBIEETERNAL
    """)

    if st.button("☀️ Run Morning Synthesis"):
        with st.spinner("Running synthesis..."):
            result = _ask_ollama(
                f"You are the AUBIEETERNAL morning synthesizer. "
                f"Today is {{datetime.date.today()}}. "
                f"Family {{_fam}} has completed {{len(stats.get(\'lessons_completed\',[]))}} lessons "
                f"and has a {{stats.get(\'streak_days\',0)}}-day streak. "
                f"Give them one sharp insight, one action, and one question to sit with today."
            )
        st.markdown(f"**Today's synthesis:**\\n\\n{{result}}")

# ══════════════════════════════════════════════════════════════════════════════
elif "School" in _page:
    st.title("🏫 School")
    # Load lessons from family_hud if available, else use built-in subset
    try:
        from family_hud import LESSONS
        lesson_keys = list(LESSONS.keys())
    except ImportError:
        st.warning("family_hud.py not found in this directory. Copy it here for full curriculum.")
        lesson_keys = []
        LESSONS = {{}}

    completed = set(stats.get("lessons_completed", []))
    st.markdown(f"**Progress: {{len(completed)}}/{{len(lesson_keys)}} lessons**")
    if lesson_keys:
        st.progress(len(completed)/len(lesson_keys))

    _search = st.text_input("Search lessons", placeholder="e.g. steelman, bitcoin, adversarial")
    _filtered = [k for k in lesson_keys if not _search or _search.lower() in k.lower()
                 or _search.lower() in LESSONS[k].get("title","").lower()]

    for key in _filtered[:20]:
        lesson = LESSONS[key]
        done   = key in completed
        with st.expander(f"{{\'✅\' if done else \'⭕\'}} {{lesson.get(\'title\',key)}} ({{lesson.get(\'xp\',20)}} XP)", expanded=False):
            st.markdown(f"**Topic:** {{lesson.get(\'topic\',\'\')}}")
            st.markdown(f"**Steelman:** *{{lesson.get(\'steelman\',\'\')*}}")
            st.markdown(f"**Example:** {{lesson.get(\'example\',\'\')}}")
            if lesson.get("activity"):
                st.markdown(f"**Activity:** {{lesson.get(\'activity\',\'\')}}")

            if not done:
                ans = st.text_area("Your steelman answer:", key=f"ans_{{key}}", height=80)
                if st.button("Submit + Get AI feedback", key=f"sub_{{key}}") and ans:
                    with st.spinner("Getting feedback..."):
                        feedback = _ask_ollama(
                            f"Lesson: {{lesson.get(\'title\',\'\')}}\\n"
                            f"Steelman prompt: {{lesson.get(\'steelman\',\'\')}}\\n"
                            f"Student answer: {{ans}}\\n\\n"
                            f"Give brief honest feedback (2-3 sentences). "
                            f"Is this a genuine steelman? What would make it stronger?",
                            system="You are an epistemic tutor. Be honest, direct, and constructive."
                        )
                    st.success(f"**Feedback:** {{feedback}}")
                    # Award XP
                    xp = lesson.get("xp", 20)
                    stats["lessons_completed"] = stats.get("lessons_completed",[]) + [key]
                    stats["total_xp"] = stats.get("total_xp",0) + xp
                    stats["level"] = max(1, stats["total_xp"]//100 + 1)
                    if lesson.get("grants_badge"):
                        stats.setdefault("badges",[]).append(lesson["grants_badge"])
                    if lesson.get("rune_fragments"):
                        stats["child_rune_fragments"] = stats.get("child_rune_fragments",0) + lesson["rune_fragments"]
                    _save(stats, _fam)
                    st.toast(f"+{{xp}} XP!", icon="⚡")

# ══════════════════════════════════════════════════════════════════════════════
elif "Daily Quests" in _page:
    st.title("🎮 Daily Quests")
    import random
    today = datetime.date.today().isoformat()
    rng   = random.Random(hash(f"{{_fam}}:{{today}}") % (2**32))
    QUESTS = [
        {{"id":"q1","title":"Steelman one idea you disagree with",   "xp":20,"sats":21}},
        {{"id":"q2","title":"Ask the Oracle one genuine question",    "xp":15,"sats":15}},
        {{"id":"q3","title":"Check the Bitcoin block height",         "xp":10,"sats":10}},
        {{"id":"q4","title":"Save one insight you learned today",     "xp":10,"sats":10}},
        {{"id":"q5","title":"Share one insight with a family member", "xp":20,"sats":21}},
        {{"id":"q6","title":"Complete one curriculum lesson",         "xp":25,"sats":25}},
        {{"id":"q7","title":"Name one thing that made you stronger",  "xp":15,"sats":15}},
    ]
    rng.shuffle(QUESTS)
    daily_quests = QUESTS[:5]
    completed_q  = set(stats.get("quests_completed",[]))

    c1,c2 = st.columns(2)
    c1.metric("Streak", f"{{stats.get(\'streak_days\',0)}} days 🔥")
    c2.metric("Today's XP", sum(q["xp"] for q in daily_quests if f"{{today}}:{{q[\'id\']}}" in completed_q))

    for q in daily_quests:
        qk   = f"{{today}}:{{q[\'id\']}}"
        done = qk in completed_q
        col1, col2 = st.columns([4,1])
        with col1:
            color = "#00ff88" if done else "#c8d8ff"
            st.markdown(f'<div style="color:{{color}};padding:6px 0;">{{\"✅\" if done else \"⭕\"}} {{q[\"title\"]}}</div>', unsafe_allow_html=True)
        with col2:
            if not done:
                if st.button("Done", key=f"q_{{qk}}"):
                    stats.setdefault("quests_completed",[]).append(qk)
                    stats["total_xp"] = stats.get("total_xp",0) + q["xp"]
                    stats["sats_earned"] = stats.get("sats_earned",0) + q["sats"]
                    _save(stats, _fam)
                    st.rerun()

# ══════════════════════════════════════════════════════════════════════════════
elif "Oracle" in _page:
    st.title("🔮 Oracle")
    st.markdown("Ask anything. The Oracle is honest about what it knows and doesn't know.")
    q = st.text_input("Your question:", placeholder="What is the most important thing I should understand about money?")
    if st.button("Ask Oracle") and q:
        with st.spinner("Thinking..."):
            ans = _ask_ollama(q, system=(
                "You are the AUBIEETERNAL Oracle — a sovereign epistemic tutor. "
                "Be honest about uncertainty. Steelman opposing views. "
                "Point toward first principles. Never flatter. "
                "If you don\'t know, say so clearly."
            ))
        st.markdown(f"**Oracle:** {{ans}}")
        # Log to truth log
        with open(_TRUTH_LOG, "a") as f:
            f.write(json.dumps({{
                "timestamp": datetime.datetime.now().isoformat(),
                "family_id": _fam, "question": q, "result": ans,
                "tier": 0, "daughter": "offline_oracle"
            }}) + "\\n")

# ══════════════════════════════════════════════════════════════════════════════
elif "Dashboard" in _page:
    st.title("📊 Dashboard")
    st.markdown(f"**Family:** {{_fam.title()}} &nbsp;|&nbsp; **Level {{stats.get(\'level\',1)}}**")

    lessons_done = len(stats.get("lessons_completed",[]))
    total_xp     = stats.get("total_xp", 0)
    rune_frags   = stats.get("child_rune_fragments", 0)
    badges       = stats.get("badges", [])

    col1,col2,col3,col4 = st.columns(4)
    col1.metric("Total XP",    total_xp)
    col2.metric("Lessons",     lessons_done)
    col3.metric("Rune Frags",  f"{{rune_frags}}/256")
    col4.metric("Badges",      len(badges))

    if badges:
        st.markdown("**Badges earned:**")
        st.markdown("  ".join(badges))

    # Truth log entries
    if _TRUTH_LOG.exists():
        entries = [json.loads(l) for l in _TRUTH_LOG.read_text().strip().split("\\n") if l]
        entries = [e for e in entries if e.get("family_id") == _fam]
        st.markdown(f"**Oracle queries:** {{len(entries)}}")

# ══════════════════════════════════════════════════════════════════════════════
elif "Lattice" in _page:
    st.title("🕸️ Living Lattice")
    try:
        from living_lattice import LivingLattice
        lattice = LivingLattice(_fam)
        summary = lattice.get_lattice_summary()
        stats_l = summary.get("stats", {{}})

        st.metric("Wisdom GDP", f"{{stats_l.get(\'wisdom_gdp\', 0):.2f}}/10")
        c1,c2,c3 = st.columns(3)
        c1.metric("Days Active",    stats_l.get("days_active", 0))
        c2.metric("Avg Coherence",  stats_l.get("avg_coherence_30d", 0))
        c3.metric("Trend",          stats_l.get("trend", "—").title())

        st.markdown(f"**Your anonymous Lattice ID:** `{{summary[\'lattice_id\']}}`")
        st.caption("This ID is local and never linked to your identity.")

        if st.button("📡 Publish Today's Signal"):
            result = lattice.publish_daily_signal(force=True)
            st.success(f"Signal published: coherence={{result.get(\'signal\',{{}}).get(\'avg_coherence\',0)}}")

        if st.button("🔄 Regenerate Lattice ID"):
            new_id = lattice.regenerate_lattice_id()
            st.info(f"New ID: {{new_id}}")
    except ImportError:
        st.info("Copy living_lattice.py to this directory to enable the Living Lattice.")
'''

    # Write to temp file
    app_path = DATA_DIR / "_offline_app.py"
    app_path.write_text(app_code)
    return app_path


def main():
    check_dependencies()

    app_path = write_offline_app()
    print(f"Launching AUBIEETERNAL Offline on http://localhost:{PORT}")
    print(f"Press Ctrl+C to stop.\n")

    env = os.environ.copy()
    env["STREAMLIT_SERVER_HEADLESS"] = "true"

    try:
        subprocess.run([
            sys.executable, "-m", "streamlit", "run", str(app_path),
            f"--server.port={PORT}",
            "--server.address=localhost",
            "--server.headless=true",
            "--browser.gatherUsageStats=false",
            "--theme.base=dark",
            "--theme.primaryColor=#f7931a",
            "--theme.backgroundColor=#0a0e1a",
            "--theme.secondaryBackgroundColor=#1a2233",
            "--theme.textColor=#c8d8ff",
        ], env=env)
    except KeyboardInterrupt:
        print("\n🦅 AUBIEETERNAL offline — stopped. War Eagle Eternal.")


if __name__ == "__main__":
    main()
